name: RSS to Notion

on:
  schedule:
    - cron: "0 * * * *"    # hourly (UTC). You can change this; min is */5
  workflow_dispatch: {}     # manual 'Run workflow' button

permissions:
  contents: write  # needed to push to the state branch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need refs to manage a second branch

      # Prepare a worktree for the 'state' branch under .state/
      - name: Prepare state worktree
        run: |
          git fetch origin state || true
          if git rev-parse --verify origin/state >/dev/null 2>&1; then
            git worktree add .state origin/state
          else
            # create an orphan 'state' branch with an empty state.json
            git worktree add -b state .state
            echo "[]" > .state/state.json
            pushd .state
            git config user.name "rss-to-notion-bot"
            git config user.email "rss2notion-bot@users.noreply.github.com"
            git add state.json
            git commit -m "init state branch"
            git push -u origin HEAD:state
            popd
          fi
          # copy current state into workspace root for the script
          cp .state/state.json state.json || echo "[]">state.json

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Ingest feeds → Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FEEDS: ${{ secrets.FEEDS }}
          FEEDS_OPML_URL: ${{ secrets.FEEDS_OPML_URL }}
          PROPERTY_MAP: ${{ secrets.PROPERTY_MAP }}
          NOTION_VERSION: ${{ secrets.NOTION_VERSION }}
        run: python ingest.py

      # Write updated state back to 'state' branch (not the default branch)
      - name: Commit updated state to 'state' branch
        run: |
          cp state.json .state/state.json
          pushd .state
          git config user.name "rss-to-notion-bot"
          git config user.email "rss2notion-bot@users.noreply.github.com"
          git add state.json
          git commit -m "chore: update state [skip ci]" || echo "No changes"
          git push origin HEAD:state
          popd
